<?php

namespace App\DataProviders;

abstract class CountryDataProvider
{
    public static function data(): array
    {
        return [
            ['id' => '1', 'name' => 'afghanistan'],
            ['id' => '2', 'name' => 'albania'],
            ['id' => '3', 'name' => 'algeria'],
            ['id' => '4', 'name' => 'american samoa'],
            ['id' => '5', 'name' => 'andorra'],
            ['id' => '6', 'name' => 'angola'],
            ['id' => '7', 'name' => 'anguilla'],
            ['id' => '8', 'name' => 'antarctica'],
            ['id' => '9', 'name' => 'antigua and barbuda'],
            ['id' => '10', 'name' => 'argentina'],
            ['id' => '11', 'name' => 'armenia'],
            ['id' => '12', 'name' => 'aruba'],
            ['id' => '13', 'name' => 'australia'],
            ['id' => '14', 'name' => 'austria'],
            ['id' => '15', 'name' => 'azerbaijan'],
            ['id' => '16', 'name' => 'bahamas'],
            ['id' => '17', 'name' => 'bahrain'],
            ['id' => '18', 'name' => 'bangladesh'],
            ['id' => '19', 'name' => 'barbados'],
            ['id' => '20', 'name' => 'belarus'],
            ['id' => '21', 'name' => 'belgium'],
            ['id' => '22', 'name' => 'belize'],
            ['id' => '23', 'name' => 'benin'],
            ['id' => '24', 'name' => 'bermuda'],
            ['id' => '25', 'name' => 'bhutan'],
            ['id' => '26', 'name' => 'bolivia'],
            ['id' => '27', 'name' => 'bosnia and herzegovina'],
            ['id' => '28', 'name' => 'botswana'],
            ['id' => '29', 'name' => 'bouvet island'],
            ['id' => '30', 'name' => 'brazil'],
            ['id' => '31', 'name' => 'british indian ocean territory'],
            ['id' => '32', 'name' => 'brunei darussalam'],
            ['id' => '33', 'name' => 'bulgaria'],
            ['id' => '34', 'name' => 'burkina faso'],
            ['id' => '35', 'name' => 'burundi'],
            ['id' => '36', 'name' => 'cambodia'],
            ['id' => '37', 'name' => 'cameroon'],
            ['id' => '38', 'name' => 'canada'],
            ['id' => '39', 'name' => 'cape verde'],
            ['id' => '40', 'name' => 'cayman islands'],
            ['id' => '41', 'name' => 'central african republic'],
            ['id' => '42', 'name' => 'chad'],
            ['id' => '43', 'name' => 'chile'],
            ['id' => '44', 'name' => 'china'],
            ['id' => '45', 'name' => 'christmas island'],
            ['id' => '46', 'name' => 'cocos (keeling) islands'],
            ['id' => '47', 'name' => 'colombia'],
            ['id' => '48', 'name' => 'comoros'],
            ['id' => '49', 'name' => 'congo'],
            ['id' => '50', 'name' => 'congo, democratic republic of the'],
            ['id' => '51', 'name' => 'cook islands'],
            ['id' => '52', 'name' => 'costa rica'],
            ['id' => '53', 'name' => 'cote d\'ivoire'],
            ['id' => '54', 'name' => 'croatia'],
            ['id' => '55', 'name' => 'cuba'],
            ['id' => '56', 'name' => 'cyprus'],
            ['id' => '57', 'name' => 'czech republic'],
            ['id' => '58', 'name' => 'denmark'],
            ['id' => '59', 'name' => 'djibouti'],
            ['id' => '60', 'name' => 'dominica'],
            ['id' => '61', 'name' => 'dominican republic'],
            ['id' => '62', 'name' => 'east timor'],
            ['id' => '63', 'name' => 'ecuador'],
            ['id' => '64', 'name' => 'egypt'],
            ['id' => '65', 'name' => 'el salvador'],
            ['id' => '66', 'name' => 'equatorial guinea'],
            ['id' => '67', 'name' => 'eritrea'],
            ['id' => '68', 'name' => 'estonia'],
            ['id' => '69', 'name' => 'ethiopia'],
            ['id' => '71', 'name' => 'falkland islands (malvinas)'],
            ['id' => '72', 'name' => 'faroe islands'],
            ['id' => '73', 'name' => 'fiji'],
            ['id' => '74', 'name' => 'finland'],
            ['id' => '75', 'name' => 'france'],
            ['id' => '76', 'name' => 'french guiana'],
            ['id' => '77', 'name' => 'french polynesia'],
            ['id' => '78', 'name' => 'french southern territories'],
            ['id' => '79', 'name' => 'gabon'],
            ['id' => '80', 'name' => 'gambia'],
            ['id' => '81', 'name' => 'georgia'],
            ['id' => '82', 'name' => 'germany'],
            ['id' => '83', 'name' => 'ghana'],
            ['id' => '84', 'name' => 'gibraltar'],
            ['id' => '85', 'name' => 'greece'],
            ['id' => '86', 'name' => 'greenland'],
            ['id' => '87', 'name' => 'grenada'],
            ['id' => '88', 'name' => 'guadeloupe'],
            ['id' => '89', 'name' => 'guam'],
            ['id' => '90', 'name' => 'guatemala'],
            ['id' => '91', 'name' => 'guernsey'],
            ['id' => '92', 'name' => 'guinea'],
            ['id' => '93', 'name' => 'guinea-bissau'],
            ['id' => '94', 'name' => 'guyana'],
            ['id' => '95', 'name' => 'haiti'],
            ['id' => '96', 'name' => 'heard island and mcdonald islands'],
            ['id' => '97', 'name' => 'honduras'],
            ['id' => '98', 'name' => 'hong kong'],
            ['id' => '99', 'name' => 'hungary'],
            ['id' => '100', 'name' => 'iceland'],
            ['id' => '101', 'name' => 'india'],
            ['id' => '102', 'name' => 'indonesia'],
            ['id' => '103', 'name' => 'iran, islamic republic of'],
            ['id' => '104', 'name' => 'iraq'],
            ['id' => '105', 'name' => 'ireland'],
            ['id' => '106', 'name' => 'israel'],
            ['id' => '107', 'name' => 'italy'],
            ['id' => '108', 'name' => 'jamaica'],
            ['id' => '109', 'name' => 'japan'],
            ['id' => '110', 'name' => 'jersey'],
            ['id' => '111', 'name' => 'jordan'],
            ['id' => '112', 'name' => 'kazakhstan'],
            ['id' => '113', 'name' => 'kenya'],
            ['id' => '114', 'name' => 'kiribati'],
            ['id' => '115', 'name' => 'korea, democratic people\'s republic of'],
            ['id' => '116', 'name' => 'korea, republic of'],
            ['id' => '117', 'name' => 'kuwait'],
            ['id' => '118', 'name' => 'kyrgyzstan'],
            ['id' => '120', 'name' => 'latvia'],
            ['id' => '121', 'name' => 'lebanon'],
            ['id' => '122', 'name' => 'lesotho'],
            ['id' => '123', 'name' => 'liberia'],
            ['id' => '124', 'name' => 'libyan arab jamahiriya'],
            ['id' => '125', 'name' => 'liechtenstein'],
            ['id' => '126', 'name' => 'lithuania'],
            ['id' => '127', 'name' => 'luxembourg'],
            ['id' => '129', 'name' => 'macedonia, the former yugoslav republic of'],
            ['id' => '130', 'name' => 'madagascar'],
            ['id' => '131', 'name' => 'malawi'],
            ['id' => '132', 'name' => 'malaysia'],
            ['id' => '133', 'name' => 'maldives'],
            ['id' => '134', 'name' => 'mali'],
            ['id' => '135', 'name' => 'malta'],
            ['id' => '136', 'name' => 'isle of man'],
            ['id' => '137', 'name' => 'marshall islands'],
            ['id' => '138', 'name' => 'martinique'],
            ['id' => '139', 'name' => 'mauritania'],
            ['id' => '140', 'name' => 'mauritius'],
            ['id' => '141', 'name' => 'mayotte'],
            ['id' => '142', 'name' => 'mexico'],
            ['id' => '143', 'name' => 'micronesia, federated states of'],
            ['id' => '144', 'name' => 'moldova, republic of'],
            ['id' => '145', 'name' => 'monaco'],
            ['id' => '146', 'name' => 'mongolia'],
            ['id' => '147', 'name' => 'montserrat'],
            ['id' => '148', 'name' => 'morocco'],
            ['id' => '149', 'name' => 'mozambique'],
            ['id' => '150', 'name' => 'myanmar'],
            ['id' => '151', 'name' => 'namibia'],
            ['id' => '152', 'name' => 'nauru'],
            ['id' => '153', 'name' => 'nepal'],
            ['id' => '154', 'name' => 'netherlands antilles'],
            ['id' => '155', 'name' => 'netherlands'],
            ['id' => '156', 'name' => 'new caledonia'],
            ['id' => '157', 'name' => 'new zealand'],
            ['id' => '158', 'name' => 'nicaragua'],
            ['id' => '159', 'name' => 'niger'],
            ['id' => '160', 'name' => 'nigeria'],
            ['id' => '161', 'name' => 'niue'],
            ['id' => '162', 'name' => 'norfolk island'],
            ['id' => '163', 'name' => 'northern mariana islands'],
            ['id' => '164', 'name' => 'norway'],
            ['id' => '165', 'name' => 'oman'],
            ['id' => '166', 'name' => 'pakistan'],
            ['id' => '167', 'name' => 'palau'],
            ['id' => '168', 'name' => 'palestinian territory, occupied'],
            ['id' => '169', 'name' => 'panama'],
            ['id' => '170', 'name' => 'papua new guinea'],
            ['id' => '171', 'name' => 'paraguay'],
            ['id' => '172', 'name' => 'peru'],
            ['id' => '173', 'name' => 'philippines'],
            ['id' => '174', 'name' => 'pitcairn'],
            ['id' => '175', 'name' => 'poland'],
            ['id' => '176', 'name' => 'portugal'],
            ['id' => '177', 'name' => 'puerto rico'],
            ['id' => '178', 'name' => 'qatar'],
            ['id' => '179', 'name' => 'reunion'],
            ['id' => '180', 'name' => 'romania'],
            ['id' => '181', 'name' => 'russian federation'],
            ['id' => '182', 'name' => 'rwanda'],
            ['id' => '183', 'name' => 'saint helena'],
            ['id' => '184', 'name' => 'saint kitts and nevis'],
            ['id' => '185', 'name' => 'saint lucia'],
            ['id' => '186', 'name' => 'saint pierre and miquelon'],
            ['id' => '187', 'name' => 'saint vincent and the grenadines'],
            ['id' => '188', 'name' => 'samoa'],
            ['id' => '189', 'name' => 'san marino'],
            ['id' => '190', 'name' => 'sao tome and principe'],
            ['id' => '191', 'name' => 'saudi arabia'],
            ['id' => '192', 'name' => 'senegal'],
            ['id' => '193', 'name' => 'serbia'],
            ['id' => '194', 'name' => 'seychelles'],
            ['id' => '195', 'name' => 'sierra leone'],
            ['id' => '196', 'name' => 'singapore'],
            ['id' => '197', 'name' => 'slovakia'],
            ['id' => '198', 'name' => 'slovenia'],
            ['id' => '200', 'name' => 'solomon islands'],
            ['id' => '201', 'name' => 'somalia'],
            ['id' => '202', 'name' => 'south africa'],
            ['id' => '203', 'name' => 'south georgia and the south sandwich islands'],
            ['id' => '204', 'name' => 'south sudan'],
            ['id' => '205', 'name' => 'spain'],
            ['id' => '206', 'name' => 'sri lanka'],
            ['id' => '207', 'name' => 'sudan'],
            ['id' => '208', 'name' => 'suriname'],
            ['id' => '209', 'name' => 'svalbard and jan mayen'],
            ['id' => '210', 'name' => 'swaziland'],
            ['id' => '211', 'name' => 'sweden'],
            ['id' => '212', 'name' => 'switzerland'],
            ['id' => '213', 'name' => 'syrian arab republic'],
            ['id' => '214', 'name' => 'taiwan, province of china'],
            ['id' => '215', 'name' => 'tajikistan'],
            ['id' => '216', 'name' => 'tanzania, united republic of'],
            ['id' => '217', 'name' => 'thailand'],
            ['id' => '218', 'name' => 'togo'],
            ['id' => '219', 'name' => 'tokelau'],
            ['id' => '220', 'name' => 'tonga'],
            ['id' => '221', 'name' => 'trinidad and tobago'],
            ['id' => '222', 'name' => 'tunisia'],
            ['id' => '223', 'name' => 'turkey'],
            ['id' => '224', 'name' => 'turkmenistan'],
            ['id' => '225', 'name' => 'turks and caicos islands'],
            ['id' => '226', 'name' => 'tuvalu'],
            ['id' => '227', 'name' => 'uganda'],
            ['id' => '228', 'name' => 'ukraine'],
            ['id' => '229', 'name' => 'united arab emirates'],
            ['id' => '230', 'name' => 'united kingdom'],
            ['id' => '231', 'name' => 'united states'],
            ['id' => '232', 'name' => 'united states minor outlying islands'],
            ['id' => '233', 'name' => 'uruguay'],
            ['id' => '234', 'name' => 'uzbekistan'],
            ['id' => '235', 'name' => 'vanuatu'],
            ['id' => '236', 'name' => 'vatican city state (holy see)'],
            ['id' => '237', 'name' => 'venezuela'],
            ['id' => '238', 'name' => 'vietnam'],
            ['id' => '239', 'name' => 'virgin islands, british'],
            ['id' => '240', 'name' => 'virgin islands, u.s.'],
            ['id' => '241', 'name' => 'wallis and futuna'],
            ['id' => '242', 'name' => 'western sahara'],
            ['id' => '243', 'name' => 'yemen'],
            ['id' => '245', 'name' => 'zambia'],
            ['id' => '246', 'name' => 'zimbabwe']
        ];
    }

    public static function dataCountryCode(): array
    {
        return [
            ["name"=>"Afghanistan","code"=>"AF","phone"=>93],
            ["name"=>"Aland Islands","code"=>"AX","phone"=>358],
            ["name"=>"Albania","code"=>"AL","phone"=>355],
            ["name"=>"Algeria","code"=>"DZ","phone"=>213],
            ["name"=>"American Samoa","code"=>"AS","phone"=>1684],
            ["name"=>"Andorra","code"=>"AD","phone"=>376],
            ["name"=>"Angola","code"=>"AO","phone"=>244],
            ["name"=>"Anguilla","code"=>"AI","phone"=>1264],
            ["name"=>"Antarctica","code"=>"AQ","phone"=>672],
            ["name"=>"Antigua and Barbuda","code"=>"AG","phone"=>1268],
            ["name"=>"Argentina","code"=>"AR","phone"=>54],
            ["name"=>"Armenia","code"=>"AM","phone"=>374],
            ["name"=>"Aruba","code"=>"AW","phone"=>297],
            ["name"=>"Australia","code"=>"AU","phone"=>61],
            ["name"=>"Austria","code"=>"AT","phone"=>43],
            ["name"=>"Azerbaijan","code"=>"AZ","phone"=>994],
            ["name"=>"Bahamas","code"=>"BS","phone"=>1242],
            ["name"=>"Bahrain","code"=>"BH","phone"=>973],
            ["name"=>"Bangladesh","code"=>"BD","phone"=>880],
            ["name"=>"Barbados","code"=>"BB","phone"=>1246],
            ["name"=>"Belarus","code"=>"BY","phone"=>375],
            ["name"=>"Belgium","code"=>"BE","phone"=>32],
            ["name"=>"Belize","code"=>"BZ","phone"=>501],
            ["name"=>"Benin","code"=>"BJ","phone"=>229],
            ["name"=>"Bermuda","code"=>"BM","phone"=>1441],
            ["name"=>"Bhutan","code"=>"BT","phone"=>975],
            ["name"=>"Bolivia","code"=>"BO","phone"=>591],
            ["name"=>"Bonaire, Sint Eustatius and Saba","code"=>"BQ","phone"=>599],
            ["name"=>"Bosnia and Herzegovina","code"=>"BA","phone"=>387],
            ["name"=>"Botswana","code"=>"BW","phone"=>267],
            ["name"=>"Bouvet Island","code"=>"BV","phone"=>55],
            ["name"=>"Brazil","code"=>"BR","phone"=>55],
            ["name"=>"British Indian Ocean Territory","code"=>"IO","phone"=>246],
            ["name"=>"Brunei Darussalam","code"=>"BN","phone"=>673],
            ["name"=>"Bulgaria","code"=>"BG","phone"=>359],
            ["name"=>"Burkina Faso","code"=>"BF","phone"=>226],
            ["name"=>"Burundi","code"=>"BI","phone"=>257],
            ["name"=>"Cambodia","code"=>"KH","phone"=>855],
            ["name"=>"Cameroon","code"=>"CM","phone"=>237],
            ["name"=>"Canada","code"=>"CA","phone"=>1],
            ["name"=>"Cape Verde","code"=>"CV","phone"=>238],
            ["name"=>"Cayman Islands","code"=>"KY","phone"=>1345],
            ["name"=>"Central African Republic","code"=>"CF","phone"=>236],
            ["name"=>"Chad","code"=>"TD","phone"=>235],
            ["name"=>"Chile","code"=>"CL","phone"=>56],
            ["name"=>"China","code"=>"CN","phone"=>86],
            ["name"=>"Christmas Island","code"=>"CX","phone"=>61],
            ["name"=>"Cocos (Keeling) Islands","code"=>"CC","phone"=>672],
            ["name"=>"Colombia","code"=>"CO","phone"=>57],
            ["name"=>"Comoros","code"=>"KM","phone"=>269],
            ["name"=>"Congo","code"=>"CG","phone"=>242],
            ["name"=>"Congo, Democratic Republic of the","code"=>"CD","phone"=>242],
            ["name"=>"Cook Islands","code"=>"CK","phone"=>682],
            ["name"=>"Costa Rica","code"=>"CR","phone"=>506],
            ["name"=>"Cote D'Ivoire","code"=>"CI","phone"=>225],
            ["name"=>"Croatia","code"=>"HR","phone"=>385],
            ["name"=>"Cuba","code"=>"CU","phone"=>53],
            ["name"=>"Curacao","code"=>"CW","phone"=>599],
            ["name"=>"Cyprus","code"=>"CY","phone"=>357],
            ["name"=>"Czech Republic","code"=>"CZ","phone"=>420],
            ["name"=>"Denmark","code"=>"DK","phone"=>45],
            ["name"=>"Djibouti","code"=>"DJ","phone"=>253],
            ["name"=>"Dominica","code"=>"DM","phone"=>1767],
            ["name"=>"Dominican Republic","code"=>"DO","phone"=>1809],
            ["name"=>"Ecuador","code"=>"EC","phone"=>593],
            ["name"=>"Egypt","code"=>"EG","phone"=>20],
            ["name"=>"El Salvador","code"=>"SV","phone"=>503],
            ["name"=>"Equatorial Guinea","code"=>"GQ","phone"=>240],
            ["name"=>"Eritrea","code"=>"ER","phone"=>291],
            ["name"=>"Estonia","code"=>"EE","phone"=>372],
            ["name"=>"Ethiopia","code"=>"ET","phone"=>251],
            ["name"=>"Falkland Islands (Malvinas)","code"=>"FK","phone"=>500],
            ["name"=>"Faroe Islands","code"=>"FO","phone"=>298],
            ["name"=>"Fiji","code"=>"FJ","phone"=>679],
            ["name"=>"Finland","code"=>"FI","phone"=>358],
            ["name"=>"France","code"=>"FR","phone"=>33],
            ["name"=>"French Guiana","code"=>"GF","phone"=>594],
            ["name"=>"French Polynesia","code"=>"PF","phone"=>689],
            ["name"=>"French Southern Territories","code"=>"TF","phone"=>262],
            ["name"=>"Gabon","code"=>"GA","phone"=>241],
            ["name"=>"Gambia","code"=>"GM","phone"=>220],
            ["name"=>"Georgia","code"=>"GE","phone"=>995],
            ["name"=>"Germany","code"=>"DE","phone"=>49],
            ["name"=>"Ghana","code"=>"GH","phone"=>233],
            ["name"=>"Gibraltar","code"=>"GI","phone"=>350],
            ["name"=>"Greece","code"=>"GR","phone"=>30],
            ["name"=>"Greenland","code"=>"GL","phone"=>299],
            ["name"=>"Grenada","code"=>"GD","phone"=>1473],
            ["name"=>"Guadeloupe","code"=>"GP","phone"=>590],
            ["name"=>"Guam","code"=>"GU","phone"=>1671],
            ["name"=>"Guatemala","code"=>"GT","phone"=>502],
            ["name"=>"Guernsey","code"=>"GG","phone"=>44],
            ["name"=>"Guinea","code"=>"GN","phone"=>224],
            ["name"=>"Guinea-Bissau","code"=>"GW","phone"=>245],
            ["name"=>"Guyana","code"=>"GY","phone"=>592],
            ["name"=>"Haiti","code"=>"HT","phone"=>509],
            ["name"=>"Heard Island and Mcdonald Islands","code"=>"HM","phone"=>0],
            ["name"=>"Vatican City State (holy see)","code"=>"VA","phone"=>39],
            ["name"=>"Honduras","code"=>"HN","phone"=>504],
            ["name"=>"Hong Kong","code"=>"HK","phone"=>852],
            ["name"=>"Hungary","code"=>"HU","phone"=>36],
            ["name"=>"Iceland","code"=>"IS","phone"=>354],
            ["name"=>"India","code"=>"IN","phone"=>91],
            ["name"=>"Indonesia","code"=>"ID","phone"=>62],
            ["name"=>"Iran, Islamic Republic of","code"=>"IR","phone"=>98],
            ["name"=>"Iraq","code"=>"IQ","phone"=>964],
            ["name"=>"Ireland","code"=>"IE","phone"=>353],
            ["name"=>"Isle of Man","code"=>"IM","phone"=>44],
            ["name"=>"Israel","code"=>"IL","phone"=>972],
            ["name"=>"Italy","code"=>"IT","phone"=>39],
            ["name"=>"Jamaica","code"=>"JM","phone"=>1876],
            ["name"=>"Japan","code"=>"JP","phone"=>81],
            ["name"=>"Jersey","code"=>"JE","phone"=>44],
            ["name"=>"Jordan","code"=>"JO","phone"=>962],
            ["name"=>"Kazakhstan","code"=>"KZ","phone"=>7],
            ["name"=>"Kenya","code"=>"KE","phone"=>254],
            ["name"=>"Kiribati","code"=>"KI","phone"=>686],
            ["name"=>"Korea, Democratic People's Republic of","code"=>"KP","phone"=>850],
            ["name"=>"Korea, Republic of","code"=>"KR","phone"=>82],
            ["name"=>"Kosovo","code"=>"XK","phone"=>381],
            ["name"=>"Kuwait","code"=>"KW","phone"=>965],
            ["name"=>"Kyrgyzstan","code"=>"KG","phone"=>996],
            ["name"=>"Lao People's Democratic Republic","code"=>"LA","phone"=>856],
            ["name"=>"Latvia","code"=>"LV","phone"=>371],
            ["name"=>"Lebanon","code"=>"LB","phone"=>961],
            ["name"=>"Lesotho","code"=>"LS","phone"=>266],
            ["name"=>"Liberia","code"=>"LR","phone"=>231],
            ["name"=>"Libyan Arab Jamahiriya","code"=>"LY","phone"=>218],
            ["name"=>"Liechtenstein","code"=>"LI","phone"=>423],
            ["name"=>"Lithuania","code"=>"LT","phone"=>370],
            ["name"=>"Luxembourg","code"=>"LU","phone"=>352],
            ["name"=>"Macao","code"=>"MO","phone"=>853],
            ["name"=>"Macedonia, the Former Yugoslav Republic of","code"=>"MK","phone"=>389],
            ["name"=>"Madagascar","code"=>"MG","phone"=>261],
            ["name"=>"Malawi","code"=>"MW","phone"=>265],
            ["name"=>"Malaysia","code"=>"MY","phone"=>60],
            ["name"=>"Maldives","code"=>"MV","phone"=>960],
            ["name"=>"Mali","code"=>"ML","phone"=>223],
            ["name"=>"Malta","code"=>"MT","phone"=>356],
            ["name"=>"Marshall Islands","code"=>"MH","phone"=>692],
            ["name"=>"Martinique","code"=>"MQ","phone"=>596],
            ["name"=>"Mauritania","code"=>"MR","phone"=>222],
            ["name"=>"Mauritius","code"=>"MU","phone"=>230],
            ["name"=>"Mayotte","code"=>"YT","phone"=>269],
            ["name"=>"Mexico","code"=>"MX","phone"=>52],
            ["name"=>"Micronesia, Federated States of","code"=>"FM","phone"=>691],
            ["name"=>"Moldova, Republic of","code"=>"MD","phone"=>373],
            ["name"=>"Monaco","code"=>"MC","phone"=>377],
            ["name"=>"Mongolia","code"=>"MN","phone"=>976],
            ["name"=>"Montenegro","code"=>"ME","phone"=>382],
            ["name"=>"Montserrat","code"=>"MS","phone"=>1664],
            ["name"=>"Morocco","code"=>"MA","phone"=>212],
            ["name"=>"Mozambique","code"=>"MZ","phone"=>258],
            ["name"=>"Myanmar","code"=>"MM","phone"=>95],
            ["name"=>"Namibia","code"=>"NA","phone"=>264],
            ["name"=>"Nauru","code"=>"NR","phone"=>674],
            ["name"=>"Nepal","code"=>"NP","phone"=>977],
            ["name"=>"Netherlands","code"=>"NL","phone"=>31],
            ["name"=>"Netherlands Antilles","code"=>"AN","phone"=>599],
            ["name"=>"New Caledonia","code"=>"NC","phone"=>687],
            ["name"=>"New Zealand","code"=>"NZ","phone"=>64],
            ["name"=>"Nicaragua","code"=>"NI","phone"=>505],
            ["name"=>"Niger","code"=>"NE","phone"=>227],
            ["name"=>"Nigeria","code"=>"NG","phone"=>234],
            ["name"=>"Niue","code"=>"NU","phone"=>683],
            ["name"=>"Norfolk Island","code"=>"NF","phone"=>672],
            ["name"=>"Northern Mariana Islands","code"=>"MP","phone"=>1670],
            ["name"=>"Norway","code"=>"NO","phone"=>47],
            ["name"=>"Oman","code"=>"OM","phone"=>968],
            ["name"=>"Pakistan","code"=>"PK","phone"=>92],
            ["name"=>"Palau","code"=>"PW","phone"=>680],
            ["name"=>"Palestinian Territory, Occupied","code"=>"PS","phone"=>970],
            ["name"=>"Panama","code"=>"PA","phone"=>507],
            ["name"=>"Papua New Guinea","code"=>"PG","phone"=>675],
            ["name"=>"Paraguay","code"=>"PY","phone"=>595],
            ["name"=>"Peru","code"=>"PE","phone"=>51],
            ["name"=>"Philippines","code"=>"PH","phone"=>63],
            ["name"=>"Pitcairn","code"=>"PN","phone"=>64],
            ["name"=>"Poland","code"=>"PL","phone"=>48],
            ["name"=>"Portugal","code"=>"PT","phone"=>351],
            ["name"=>"Puerto Rico","code"=>"PR","phone"=>1787],
            ["name"=>"Qatar","code"=>"QA","phone"=>974],
            ["name"=>"Reunion","code"=>"RE","phone"=>262],
            ["name"=>"Romania","code"=>"RO","phone"=>40],
            ["name"=>"Russian Federation","code"=>"RU","phone"=>70],
            ["name"=>"Rwanda","code"=>"RW","phone"=>250],
            ["name"=>"Saint Barthelemy","code"=>"BL","phone"=>590],
            ["name"=>"Saint Helena","code"=>"SH","phone"=>290],
            ["name"=>"Saint Kitts and Nevis","code"=>"KN","phone"=>1869],
            ["name"=>"Saint Lucia","code"=>"LC","phone"=>1758],
            ["name"=>"Saint Martin","code"=>"MF","phone"=>590],
            ["name"=>"Saint Pierre and Miquelon","code"=>"PM","phone"=>508],
            ["name"=>"Saint Vincent and the Grenadines","code"=>"VC","phone"=>1784],
            ["name"=>"Samoa","code"=>"WS","phone"=>684],
            ["name"=>"San Marino","code"=>"SM","phone"=>378],
            ["name"=>"Sao Tome and Principe","code"=>"ST","phone"=>239],
            ["name"=>"Saudi Arabia","code"=>"SA","phone"=>966],
            ["name"=>"Senegal","code"=>"SN","phone"=>221],
            ["name"=>"Serbia","code"=>"RS","phone"=>381],
            ["name"=>"Serbia and Montenegro","code"=>"CS","phone"=>381],
            ["name"=>"Seychelles","code"=>"SC","phone"=>248],
            ["name"=>"Sierra Leone","code"=>"SL","phone"=>232],
            ["name"=>"Singapore","code"=>"SG","phone"=>65],
            ["name"=>"Sint Maarten","code"=>"SX","phone"=>1],
            ["name"=>"Slovakia","code"=>"SK","phone"=>421],
            ["name"=>"Slovenia","code"=>"SI","phone"=>386],
            ["name"=>"Solomon Islands","code"=>"SB","phone"=>677],
            ["name"=>"Somalia","code"=>"SO","phone"=>252],
            ["name"=>"South Africa","code"=>"ZA","phone"=>27],
            ["name"=>"South Georgia and the South Sandwich Islands","code"=>"GS","phone"=>500],
            ["name"=>"South Sudan","code"=>"SS","phone"=>211],
            ["name"=>"Spain","code"=>"ES","phone"=>34],
            ["name"=>"Sri Lanka","code"=>"LK","phone"=>94],
            ["name"=>"Sudan","code"=>"SD","phone"=>249],
            ["name"=>"Suriname","code"=>"SR","phone"=>597],
            ["name"=>"Svalbard and Jan Mayen","code"=>"SJ","phone"=>47],
            ["name"=>"Swaziland","code"=>"SZ","phone"=>268],
            ["name"=>"Sweden","code"=>"SE","phone"=>46],
            ["name"=>"Switzerland","code"=>"CH","phone"=>41],
            ["name"=>"Syrian Arab Republic","code"=>"SY","phone"=>963],
            ["name"=>"Taiwan, Province of China","code"=>"TW","phone"=>886],
            ["name"=>"Tajikistan","code"=>"TJ","phone"=>992],
            ["name"=>"Tanzania, United Republic of","code"=>"TZ","phone"=>255],
            ["name"=>"Thailand","code"=>"TH","phone"=>66],
            ["name"=>"East Timor","code"=>"TL","phone"=>670],
            ["name"=>"Togo","code"=>"TG","phone"=>228],
            ["name"=>"Tokelau","code"=>"TK","phone"=>690],
            ["name"=>"Tonga","code"=>"TO","phone"=>676],
            ["name"=>"Trinidad and Tobago","code"=>"TT","phone"=>1868],
            ["name"=>"Tunisia","code"=>"TN","phone"=>216],
            ["name"=>"Turkey","code"=>"TR","phone"=>90],
            ["name"=>"Turkmenistan","code"=>"TM","phone"=>7370],
            ["name"=>"Turks and Caicos Islands","code"=>"TC","phone"=>1649],
            ["name"=>"Tuvalu","code"=>"TV","phone"=>688],
            ["name"=>"Uganda","code"=>"UG","phone"=>256],
            ["name"=>"Ukraine","code"=>"UA","phone"=>380],
            ["name"=>"United Arab Emirates","code"=>"AE","phone"=>971],
            ["name"=>"United Kingdom","code"=>"GB","phone"=>44],
            ["name"=>"United States","code"=>"US","phone"=>1],
            ["name"=>"United States Minor Outlying Islands","code"=>"UM","phone"=>1],
            ["name"=>"Uruguay","code"=>"UY","phone"=>598],
            ["name"=>"Uzbekistan","code"=>"UZ","phone"=>998],
            ["name"=>"Vanuatu","code"=>"VU","phone"=>678],
            ["name"=>"Venezuela","code"=>"VE","phone"=>58],
            ["name"=>"VietNam","code"=>"VN","phone"=>84],
            ["name"=>"Virgin Islands, British","code"=>"VG","phone"=>1284],
            ["name"=>"Virgin Islands, U.s.","code"=>"VI","phone"=>1340],
            ["name"=>"Wallis and Futuna","code"=>"WF","phone"=>681],
            ["name"=>"Western Sahara","code"=>"EH","phone"=>212],
            ["name"=>"Yemen","code"=>"YE","phone"=>967],
            ["name"=>"Zambia","code"=>"ZM","phone"=>260],
            ["name"=>"Zimbabwe","code"=>"ZW","phone"=>263]
        ];
    }
}
